apiVersion: v1
kind: Service
metadata:
  name: app-product
  labels:
    app: app-product
spec:
  type: ClusterIP
  selector:
    app: app-product
  ports:
    - name: http
      port: 80
      targetPort: 8081
