apiVersion: v1
kind: Service
metadata:
  name: product-ms
  labels:
    app: product-ms
spec:
  type: ClusterIP
  selector:
    app: product-ms
  ports:
    - name: http
      port: 80
      targetPort: 8080
