apiVersion: v1
kind: Secret
metadata:
  name: product-ms-secrets
  labels:
    app: product-ms
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: ${MONGODB_URI}
  MONGODB_USERNAME: ${MONGODB_USERNAME}
  MONGODB_PASSWORD: ${MONGODB_PASSWORD}
